---
- name: Write Configuration File
  ansible.builtin.template: 
    src: templates/sentinel.j2
    dest: "{{ redis_base_dir }}{{ confDir }}{{ sentinel_config_file_name }}"
    owner: "{{ username }}"
    group: "{{ usergroup }}"
    backup: yes

- name: Create Log File
  ansible.builtin.file: 
    path: "{{ redis_base_dir }}{{ logDir }}{{ sentinel_log_file_name }}"
    state: touch
    force: true
    owner: "{{ username }}"
    group: "{{ usergroup }}"

- name: Create sentinel running  dir
  ansible.builtin.file: 
     path: "{{ redis_base_dir }}{{ sentinel_running_dir }}"
     state: directory
     force: true
     owner: "{{ username }}"
     group: "{{ usergroup }}"
