---

- name: Touch Configuration File
  ansible.builtin.file:
    path: "/home/{{ username }}/redis/conf/{{ slave_config_file_name }}"
    force: true
    state: touch
    owner: "{{ username }}"
    group: "{{ usergroup }}"

- name: Touch Log file
  ansible.builtin.file:
    path: "/home/{{ username }}/redis/logs/{{ slave_log_file_name }}"
    force: true
    state: touch
    owner: "{{ username }}"
    group: "{{ usergroup }}"

- name: Write Configuration File
  ansible.builtin.template:
    src: templates/redis-6379.j2
    dest: "/home/{{ username }}/redis/conf/{{ slave_config_file_name }}"
    owner: "{{ username }}"
    group: "{{ usergroup }}"
    backup: yes
