---
- name: Test connectedness
  ansible.builtin.wait_for:
    host: 192.168.40.130
    port: 2222
    state: started
    delay: 0
    timeout: 1
    sleep: 1
  register: result
  ignore_errors: true

- name: Unreacable
  ansible.builtin.debug:
    msg: "Destination unreachable"
  when: result.failed==true
