- name: Tell if exists 
  ansible.builtin.stat: 
    path: "/home/{{ username }}/redis"
  register: st

- name: Backup redis dir if exists
  ansible.builtin.copy:
    src: "/home/{{ username }}/redis"
    dest: "/home/{{ username }}/redis.{{ ansible_date_time.date }}.bak"
    remote_src: yes
  when: st.stat.exists == true
 
- name: Create Redis Main Directory
  ansible.builtin.file:
    path: "/home/{{ username }}/redis/{{ item }}"
    force: true
    state: directory
    owner: "{{ username }}"
    group: "{{ usergroup }}"
  loop: 
    - data
    - src
    - conf
    - logs
