- name: Tell if exists 
  ansible.builtin.stat: 
    path: "{{ redis_base_dir }}"
  register: st

- name: Backup redis dir if exists
  ansible.builtin.copy:
    src: "{{ redis_base_dir }}"
    dest: "{{ redis_base_dir }}.{{ ansible_date_time.date }}.bak"
    remote_src: yes
  when: st.stat.exists == true
 
- name: Create Redis Main Directory
  ansible.builtin.file:
    path: "{{ redis_base_dir }}/{{ item }}"
    force: true
    state: directory
    owner: "{{ username }}"
    group: "{{ usergroup }}"
  loop: 
    - data
    - src
    - conf
    - logs
